import assert from 'node:assert/strict';
import {and,eq,inArray} from 'drizzle-orm';
import {getDb,getPostgresClient} from '@/db';
import * as schema from '@/db/schema';
import {menuItems,lostFound,inventoryMovements,tours,participants,communicationDrafts} from '@/db/operational-schema';
import {GET,POST} from '@/api/operations/route';
import {POST as travelPOST} from '@/api/travel/workflows/route';
import {createSessionForUser} from '@/services/auth/local-session';
import {BillingService} from '@/modules/billing/service';
import type {ReservationContext} from '@/services/reservations/types';

if(process.env.APP_MODE!=='production'||process.env.LOCAL_AUTH_ENABLED!=='true'||!['localhost','127.0.0.1'].includes(new URL(process.env.DATABASE_URL??'http://invalid').hostname))throw new Error('This verification requires a localhost production database with local auth enabled.');
const db=getDb(),org=crypto.randomUUID(),property=crypto.randomUUID(),otherProperty=crypto.randomUUID(),owner=crypto.randomUUID(),guest=crypto.randomUUID(),reservation=crypto.randomUUID(),packageId=crypto.randomUUID(),inquiryId=crypto.randomUUID();
const now=new Date().toISOString(),today=now.slice(0,10),tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);
let checks=0;
const check=(value:unknown,message:string)=>{assert.ok(value,message);checks++;};
type Row=Record<string,unknown>;
const request=(token:string,body?:Row)=>new Request(`http://localhost/api/operations?propertyId=${property}`,{method:body?'POST':'GET',headers:{cookie:`hotel_session=${token}`,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});
async function call(token:string,body:Row,status=200){const response=await POST(request(token,body)),json=await response.json() as Row;assert.equal(response.status,status,JSON.stringify({body:{action:body.action},result:json}));checks++;return json;}
try {
 await db.insert(schema.organisations).values({id:org,name:'Temporary workflow verification',createdAt:now});
 await db.insert(schema.properties).values([{id:property,organisationId:org,name:'Verification Hotel',code:'VERIFY',city:'Test',timezone:'Asia/Kolkata',kycRequired:false,lastSyncAt:now},{id:otherProperty,organisationId:org,name:'Other Property',code:'OTHER',city:'Test',timezone:'Asia/Kolkata',lastSyncAt:now}]);
 await db.insert(schema.appUsers).values({id:owner,organisationId:org,propertyId:property,name:'Verification Owner',email:`${owner}@example.test`,authProvider:'local-session',authSubject:`${owner}@example.test`,role:'OWNER',active:true,createdAt:now});
 const {token}=await createSessionForUser(owner);
 const unauth=await POST(request('',{action:'SAVE_ROOM'}));check(unauth.status===401,'Unauthenticated request rejected');
 const room=await call(token,{action:'SAVE_ROOM',number:'101',roomType:'Deluxe',floor:1,baseRatePaise:100000});
 await call(token,{action:'SAVE_ROOM',number:'101',roomType:'Deluxe',floor:1,baseRatePaise:100000},409);
 await call(token,{action:'SAVE_ROOM',id:room.id,expectedVersion:1,number:'101',roomType:'Deluxe',floor:1,baseRatePaise:120000});
 await call(token,{action:'SAVE_ROOM',id:room.id,expectedVersion:1,number:'101',roomType:'Deluxe',floor:1,baseRatePaise:1},409);
 const hk=await call(token,{action:'SAVE_STAFF',name:'Verification Housekeeper',email:`hk-${org}@example.test`,role:'HOUSEKEEPING',active:true,password:crypto.randomUUID()});
 const restaurant=await call(token,{action:'SAVE_STAFF',name:'Verification Restaurant',email:`restaurant-${org}@example.test`,role:'RESTAURANT',active:true,password:crypto.randomUUID()});
 const {token:hkToken}=await createSessionForUser(String(hk.id)),{token:restaurantToken}=await createSessionForUser(String(restaurant.id));
 await call(hkToken,{action:'SAVE_STAFF',name:'Forged',email:'forged@example.test',role:'MANAGER',active:true},403);
 await call(token,{action:'SAVE_STAFF',name:'Owner escalation',email:`bad-${org}@example.test`,role:'OWNER',active:true,password:crypto.randomUUID()},403);
 await call(token,{action:'SAVE_PROPERTY',name:'Updated Verification',city:'Test City',expectedVersion:1,checkInTime:'14:00',checkOutTime:'11:00',defaultTaxRateBps:500});
 const task=await call(token,{action:'CREATE_HOUSEKEEPING_TASK',roomId:room.id,taskType:'CHECKOUT_CLEANING',priority:'HIGH'});
 await call(token,{action:'CREATE_HOUSEKEEPING_TASK',roomId:room.id,taskType:'CHECKOUT_CLEANING',priority:'HIGH'},409);
 await call(restaurantToken,{action:'RECORD_HOUSEKEEPING_OUTCOME',taskId:task.id,expectedVersion:1,outcome:'DONE'},403);
 await call(hkToken,{action:'RECORD_HOUSEKEEPING_OUTCOME',taskId:task.id,expectedVersion:1,outcome:'DONE'},403);
 await call(token,{action:'ASSIGN_HOUSEKEEPING_TASK',taskId:task.id,assigneeId:hk.id,expectedVersion:1});
 const hq=await (await GET(request(hkToken))).json();check(hq.housekeeping.length===1&&hq.housekeeping[0].id===task.id,'Housekeeper sees assigned task');check(hq.inventory.length===0&&hq.restaurantOrders.length===0&&hq.staff.length===0,'Housekeeper cannot read financial/staff/stock data');
 await call(hkToken,{action:'RECORD_HOUSEKEEPING_OUTCOME',taskId:task.id,expectedVersion:2,outcome:'DONE'});
 const maintenance=await call(token,{action:'CREATE_MAINTENANCE',roomId:room.id,issue:'Test repair',severity:'HIGH',category:'Electrical'});
 const [blockedRoom]=await db.select().from(schema.rooms).where(eq(schema.rooms.id,String(room.id)));check(blockedRoom.operationalStatus==='MAINTENANCE','Maintenance blocks room');
 await call(token,{action:'RESOLVE_MAINTENANCE',id:maintenance.id,expectedVersion:1});
 const [dirtyRoom]=await db.select().from(schema.rooms).where(eq(schema.rooms.id,String(room.id)));check(dirtyRoom.operationalStatus==='VACANT_DIRTY','Resolution returns room to cleaning');
 const pending=await db.select().from(schema.housekeepingTasks).where(and(eq(schema.housekeepingTasks.roomId,String(room.id)),eq(schema.housekeepingTasks.status,'UNASSIGNED')));check(pending.length===1,'One actionable cleaning task after maintenance');
 const stock=await call(token,{action:'UPSERT_INVENTORY',name:'Test Towels',category:'Linen',department:'HOTEL',unit:'pieces',currentQuantity:10,minimumQuantity:2,unitCostPaise:100});const item=stock.item as Row;
 await call(token,{action:'MOVE_STOCK',itemId:item.id,delta:-3,reason:'Housekeeping issue',expectedUpdatedAt:item.updatedAt});
 await call(token,{action:'MOVE_STOCK',itemId:item.id,delta:-3,reason:'Stale issue',expectedUpdatedAt:item.updatedAt},409);
 const [updatedStock]=await db.select().from(schema.inventoryItems).where(eq(schema.inventoryItems.id,String(item.id)));check(updatedStock.currentQuantity===7,'Stock changes persisted');
 await call(token,{action:'MOVE_STOCK',itemId:item.id,delta:-8,reason:'Too many',expectedUpdatedAt:updatedStock.updatedAt},409);
 await call(restaurantToken,{action:'MOVE_STOCK',itemId:item.id,delta:1,reason:'Cross department',expectedUpdatedAt:updatedStock.updatedAt},404);
 const lost=await call(token,{action:'RECORD_LOST_ITEM',description:'Blue umbrella',location:'Lobby',custody:'Locker 1'});await call(token,{action:'RELEASE_LOST_ITEM',id:lost.id,expectedVersion:1,custody:'Guest receipt TEST'});
 const menu=await call(restaurantToken,{action:'SAVE_MENU_ITEM',name:'Test breakfast',category:'Breakfast',pricePaise:10000,available:true});
 await db.insert(schema.guests).values({id:guest,organisationId:org,propertyId:property,fullName:'Verification Guest',phone:'0000000000',createdAt:now,updatedAt:now});
 await db.insert(schema.reservations).values({id:reservation,organisationId:org,propertyId:property,reference:`VERIFY-${reservation}`,guestId:guest,roomId:String(room.id),roomType:'Deluxe',primaryGuestName:'Verification Guest',arrivalDate:today,departureDate:tomorrow,status:'CHECKED_IN',source:'DIRECT',createdBy:owner,updatedBy:owner,totalAmountPaise:0,balancePaise:0,createdAt:now,updatedAt:now});
 const context:ReservationContext={actor:{id:owner,name:'Verification Owner',email:`${owner}@example.test`,role:'OWNER',organisationId:org,propertyId:property},property:{id:property,organisationId:org,name:'Verification',code:'VERIFY',timezone:'Asia/Kolkata'}};
 const folio=await new BillingService().ensureFolio(context,reservation);
 const operationId=crypto.randomUUID(),order={action:'CREATE_RESTAURANT_ORDER',clientOperationId:operationId,reservationId:reservation,menuItemId:menu.id,quantity:2,orderType:'ROOM_SERVICE'};
 await Promise.all([call(restaurantToken,order),call(restaurantToken,order)]);
 await call(restaurantToken,{...order,quantity:3},409);
 const lines=await db.select().from(schema.folioLines).where(eq(schema.folioLines.folioId,folio.id)),[balance]=await db.select().from(schema.folios).where(eq(schema.folios.id,folio.id));check(lines.length===1,'Duplicate restaurant request posts exactly once');check(balance.totalPaise===21000&&balance.outstandingPaise===21000,'Menu price + property tax posted to folio');
 await call(restaurantToken,{action:'UPDATE_RESTAURANT_ORDER',id:operationId,expectedVersion:1,status:'PREPARING'});await call(restaurantToken,{action:'UPDATE_RESTAURANT_ORDER',id:operationId,expectedVersion:2,status:'READY'});await call(restaurantToken,{action:'UPDATE_RESTAURANT_ORDER',id:operationId,expectedVersion:3,status:'DELIVERED'});
 const meal=await call(restaurantToken,{action:'BOOK_MEAL',reservationId:reservation,serviceDate:today,mealPeriod:'BREAKFAST',guestCount:2});await call(restaurantToken,{action:'SERVE_MEAL',id:meal.id});
 await call(restaurantToken,{action:'BOOK_MEAL',reservationId:reservation,serviceDate:today,mealPeriod:'BREAKFAST',guestCount:2},409);
 const reference={action:'REGISTER_OFFLINE_BILL',id:crypto.randomUUID(),offlineReference:`OFF-${crypto.randomUUID()}`,bookingReference:`VERIFY-${reservation}`,deviceId:'verification-device',localAmountPaise:21000,taxPaise:1000,documentHash:'a'.repeat(64),generatedAt:now};
 await call(hkToken,reference,403);
 const registered=await call(token,reference);check(registered.status==='MATCHED','Offline reference compares current tax and total');
 await call(token,reference);
 await call(token,{...reference,localAmountPaise:20000},409);
 await call(token,{action:'VERIFY_OFFLINE_BILL',offlineBillId:reference.id});
 const mismatch=await call(token,{...reference,id:crypto.randomUUID(),offlineReference:`OFF-${crypto.randomUUID()}`,taxPaise:0});check(mismatch.status==='AMOUNT_MISMATCH','Reconciliation detects tax mismatch');
 await call(token,{action:'VERIFY_OFFLINE_BILL',offlineBillId:mismatch.id},409);
 const [unchangedFolio]=await db.select().from(schema.folios).where(eq(schema.folios.id,folio.id));check(unchangedFolio.totalPaise===21000,'Reconciliation never creates financial charges');
 const foreignRoom=crypto.randomUUID();await db.insert(schema.rooms).values({id:foreignRoom,propertyId:otherProperty,number:'999',roomType:'Test',floor:1,baseRatePaise:100,occupancyStatus:'VACANT',operationalStatus:'CLEAN',updatedAt:now});
 await call(token,{action:'CREATE_HOUSEKEEPING_TASK',roomId:foreignRoom,taskType:'STAY_SERVICE',priority:'HIGH'},404);
 await db.insert(schema.travelPackages).values({id:packageId,organisationId:org,name:'Verification package',durationDays:1,locations:'Test',capacity:5,booked:0,sellingPricePaise:10000,status:'ACTIVE'});
 const tRequest=(body:Row)=>new Request('http://localhost/api/travel/workflows',{method:'POST',headers:{cookie:`hotel_session=${token}`,'content-type':'application/json'},body:JSON.stringify(body)});
 const productResponse=await travelPOST(tRequest({action:'CREATE_TRAVEL_PRODUCT',name:'Catalog product',durationDays:2,locations:'Test destination',capacity:10,sellingPricePaise:50000}));check(productResponse.status===200,'Travel catalog product created');
 const assetResponse=await travelPOST(tRequest({action:'SAVE_TRAVEL_ASSET',name:'Test transport',category:'TRANSPORT',description:'Verification route',pricingUnit:'PER_TRIP',unitPricePaise:5000,active:true}));check(assetResponse.status===200,'Travel quote asset created');
 const tourResponse=await travelPOST(tRequest({action:'SAVE_TOUR',packageId,name:'Verification tour',departureDate:tomorrow,capacity:1,status:'SELLING'}));check(tourResponse.status===200,'Travel tour persists');const tour=await tourResponse.json();
 const participant=await travelPOST(tRequest({action:'ADD_PARTICIPANT',tourId:tour.id,name:'Verification traveller',sharing:'SINGLE'}));check(participant.status===200,'Participant persists');const full=await travelPOST(tRequest({action:'ADD_PARTICIPANT',tourId:tour.id,name:'Extra traveller',sharing:'DOUBLE'}));check(full.status===409,'Tour capacity enforced');
 const snapshot=await (await GET(request(token))).json();check(snapshot.inventoryMovements.length===2,'Stock ledger has opening + issue records');check(snapshot.menuItems.length===1&&snapshot.lostFound[0].status==='RELEASED','Snapshot reload reflects menu and custody state');check(!JSON.stringify(snapshot.staff).includes('passwordHash'),'Staff response excludes password hashes');check(snapshot.dashboardMetrics.totalRooms===1&&snapshot.dashboardMetrics.revenuePaise===21000,'Reporting aggregates authoritative records');
 const [worker]=await db.select().from(schema.appUsers).where(eq(schema.appUsers.id,String(hk.id)));await call(token,{action:'SAVE_STAFF',id:worker.id,expectedUpdatedAt:worker.updatedAt,name:worker.name,email:worker.email,role:'HOUSEKEEPING',active:false});check((await GET(request(hkToken))).status===401,'Deactivation revokes staff sessions');
 const audit=await db.select().from(schema.auditLogs).where(eq(schema.auditLogs.propertyId,property));check(audit.some(a=>a.action==='CREATE_RESTAURANT_ORDER')&&audit.some(a=>a.action==='MOVE_STOCK'),'Linked operations audited');
 process.stdout.write(JSON.stringify({status:'PASS',checks,coverage:['auth','RBAC','property isolation','staff','rooms','assignment','maintenance','inventory ledger','menu','orders','folio idempotency','meals','lost-found','tour capacity','snapshot','audit']})+'\n');
}finally{
 await db.delete(schema.offlineBills).where(eq(schema.offlineBills.propertyId,property));await db.delete(schema.travelAssets).where(eq(schema.travelAssets.organisationId,org));
 await db.delete(communicationDrafts).where(eq(communicationDrafts.organisationId,org));await db.delete(participants).where(eq(participants.organisationId,org));await db.delete(tours).where(eq(tours.organisationId,org));await db.delete(schema.travelPackages).where(eq(schema.travelPackages.organisationId,org));await db.delete(schema.inquiries).where(eq(schema.inquiries.id,inquiryId));
 await db.delete(schema.auditLogs).where(inArray(schema.auditLogs.actorId,(await db.select({id:schema.appUsers.id}).from(schema.appUsers).where(eq(schema.appUsers.organisationId,org))).map(r=>r.id)));
 await db.delete(schema.restaurantMealBookings).where(eq(schema.restaurantMealBookings.propertyId,property));await db.delete(schema.restaurantOrders).where(eq(schema.restaurantOrders.propertyId,property));await db.delete(schema.folioLines).where(eq(schema.folioLines.propertyId,property));await db.delete(schema.folios).where(eq(schema.folios.propertyId,property));await db.delete(schema.housekeepingTasks).where(eq(schema.housekeepingTasks.propertyId,property));await db.delete(schema.maintenanceTickets).where(eq(schema.maintenanceTickets.propertyId,property));await db.delete(schema.reservations).where(eq(schema.reservations.propertyId,property));await db.delete(schema.guests).where(eq(schema.guests.propertyId,property));await db.delete(inventoryMovements).where(eq(inventoryMovements.propertyId,property));await db.delete(schema.inventoryItems).where(eq(schema.inventoryItems.propertyId,property));await db.delete(menuItems).where(eq(menuItems.propertyId,property));await db.delete(lostFound).where(eq(lostFound.propertyId,property));await db.delete(schema.rooms).where(inArray(schema.rooms.propertyId,[property,otherProperty]));await db.delete(schema.appUsers).where(eq(schema.appUsers.organisationId,org));await db.delete(schema.properties).where(eq(schema.properties.organisationId,org));await db.delete(schema.organisations).where(eq(schema.organisations.id,org));await getPostgresClient().end();
}
