import { and, asc, count, desc, eq, ilike, or } from 'drizzle-orm';
import { auditLogs, guestIdentityDocuments, guests, reservationGuests, reservations, stays } from '@/db/schema';
import { getDb } from '@/db';
import { DomainError, assertRoleCan } from '@/lib/domain';
import type { ReservationContext } from '@/lib/server/reservations/types';
import { guestInputSchema, guestListSchema, guestPatchSchema, identityDocumentSchema, maskedIdentityNumber } from './validation';

function scope(context: ReservationContext) {
  if (context.actor.organisationId !== context.property.organisationId || context.actor.propertyId !== context.property.id) throw new DomainError('PROPERTY_ACCESS_DENIED','An active property context is required.',403);
}
function safeGuest(values: Record<string, unknown>) { return values; }
async function audit(context: ReservationContext, action: string, id: string, fields?: string[]) {
  const now = new Date().toISOString(); await getDb().insert(auditLogs).values({ id: crypto.randomUUID(), timestamp: now, actorId: context.actor.id, actorName: context.actor.name, role: context.actor.role, propertyId: context.property.id, deviceId: null, action, entity: 'GUEST', entityId: id, previousValue: null, newValue: fields?.join(',') ?? null, source: 'PRODUCTION_API', correlationId: crypto.randomUUID() });
}
export class GuestService {
  async list(context: ReservationContext, raw: unknown) { scope(context); assertRoleCan(context.actor.role,'guest.view'); const q=guestListSchema.parse(raw); const where=and(eq(guests.organisationId,context.actor.organisationId),eq(guests.propertyId,context.property.id),q.search?or(ilike(guests.fullName,`%${q.search}%`),ilike(guests.phone,`%${q.search}%`),ilike(guests.email,`%${q.search}%`)):undefined); const db=getDb(); const [items,total]=await Promise.all([db.select().from(guests).where(where).orderBy(asc(guests.fullName)).limit(q.pageSize).offset((q.page-1)*q.pageSize),db.select({value:count()}).from(guests).where(where)]); return {items:items.map(safeGuest),page:q.page,pageSize:q.pageSize,total:total[0]?.value??0}; }
  async get(context: ReservationContext,id:string) { scope(context); assertRoleCan(context.actor.role,'guest.view'); const row=(await getDb().select().from(guests).where(and(eq(guests.id,id),eq(guests.organisationId,context.actor.organisationId),eq(guests.propertyId,context.property.id))).limit(1))[0]; if(!row) throw new DomainError('GUEST_NOT_FOUND','Guest was not found.',404); return row; }
  async create(context: ReservationContext,raw:unknown) { scope(context); assertRoleCan(context.actor.role,'guest.create'); const input=guestInputSchema.parse(raw); const now=new Date().toISOString(),id=crypto.randomUUID(),displayName=input.displayName||`${input.firstName} ${input.lastName}`.trim(); const values={...input,email:input.email||null,id,organisationId:context.actor.organisationId,propertyId:context.property.id,fullName:displayName,displayName,createdAt:now,updatedAt:now}; await getDb().insert(guests).values(values); await audit(context,'GUEST_CREATED',id); return this.get(context,id); }
  async update(context: ReservationContext,id:string,raw:unknown) { scope(context); assertRoleCan(context.actor.role,'guest.edit'); const old=await this.get(context,id),input=guestPatchSchema.parse(raw); const first=input.firstName??old.firstName??old.fullName,last=input.lastName??old.lastName??'',display=input.displayName??`${first} ${last}`.trim(); await getDb().update(guests).set({...input,email:input.email===''?null:input.email,fullName:display,displayName:display,updatedAt:new Date().toISOString()}).where(and(eq(guests.id,id),eq(guests.organisationId,context.actor.organisationId),eq(guests.propertyId,context.property.id))); await audit(context,'GUEST_UPDATED',id,Object.keys(input)); return this.get(context,id); }
  async history(context: ReservationContext,id:string) { await this.get(context,id); const db=getDb(); const [primary,companions,stayRows]=await Promise.all([db.select({id:reservations.id,reference:reservations.reference,arrivalDate:reservations.arrivalDate,departureDate:reservations.departureDate,status:reservations.status,roomType:reservations.roomType}).from(reservations).where(and(eq(reservations.guestId,id),eq(reservations.organisationId,context.actor.organisationId),eq(reservations.propertyId,context.property.id))).orderBy(desc(reservations.arrivalDate)),db.select({id:reservations.id,reference:reservations.reference,arrivalDate:reservations.arrivalDate,departureDate:reservations.departureDate,status:reservations.status,roomType:reservations.roomType}).from(reservationGuests).innerJoin(reservations,eq(reservationGuests.reservationId,reservations.id)).where(and(eq(reservationGuests.guestId,id),eq(reservationGuests.organisationId,context.actor.organisationId),eq(reservationGuests.propertyId,context.property.id))),db.select().from(stays).where(and(eq(stays.guestId,id),eq(stays.organisationId,context.actor.organisationId),eq(stays.propertyId,context.property.id))).orderBy(desc(stays.actualCheckInAt))]); return {reservations:[...primary,...companions],stays:stayRows}; }
  async documents(context: ReservationContext,id:string) { await this.get(context,id); assertRoleCan(context.actor.role,'guest.kyc.view'); return getDb().select().from(guestIdentityDocuments).where(and(eq(guestIdentityDocuments.guestId,id),eq(guestIdentityDocuments.organisationId,context.actor.organisationId),eq(guestIdentityDocuments.propertyId,context.property.id))).orderBy(desc(guestIdentityDocuments.createdAt)); }
  async addDocument(context: ReservationContext,id:string,raw:unknown) { await this.get(context,id); assertRoleCan(context.actor.role,'guest.kyc.verify'); const input=identityDocumentSchema.parse(raw),now=new Date().toISOString(),documentId=crypto.randomUUID(); await getDb().insert(guestIdentityDocuments).values({id:documentId,organisationId:context.actor.organisationId,propertyId:context.property.id,guestId:id,documentType:input.documentType,maskedNumber:maskedIdentityNumber(input.documentType,input.last4),issuingCountry:input.issuingCountry,issuedAt:input.issuedAt,expiresAt:input.expiresAt,verified:input.verified,verifiedAt:input.verified?now:null,verifiedBy:input.verified?context.actor.id:null,createdAt:now,updatedAt:now}); await audit(context,input.verified?'GUEST_KYC_VERIFIED':'GUEST_KYC_ADDED',id,[input.documentType]); return this.documents(context,id); }
}
export const guestService=new GuestService();
