ALTER TABLE "properties" ADD COLUMN "legal_name" text;
ALTER TABLE "properties" ADD COLUMN "billing_address" text;
ALTER TABLE "properties" ADD COLUMN "billing_state" text;
ALTER TABLE "properties" ADD COLUMN "billing_state_code" text;
ALTER TABLE "properties" ADD COLUMN "gstin" text;
ALTER TABLE "properties" ADD COLUMN "invoice_prefix" text DEFAULT 'INV' NOT NULL;
ALTER TABLE "properties" ADD COLUMN "receipt_prefix" text DEFAULT 'RCT' NOT NULL;
ALTER TABLE "properties" ADD COLUMN "default_tax_rate_bps" integer DEFAULT 0 NOT NULL;
ALTER TABLE "properties" ADD COLUMN "default_tax_mode" text DEFAULT 'CGST_SGST' NOT NULL;
--> statement-breakpoint
ALTER TABLE "folios" ADD COLUMN "organisation_id" text;
ALTER TABLE "folios" ADD COLUMN "guest_id" text;
ALTER TABLE "folios" ADD COLUMN "stay_id" text;
ALTER TABLE "folios" ADD COLUMN "discount_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "taxable_amount_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "cgst_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "sgst_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "igst_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "paid_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "refunded_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "outstanding_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folios" ADD COLUMN "closed_at" timestamp with time zone;
ALTER TABLE "folios" ADD COLUMN "closed_by" text;
UPDATE "folios" f SET "organisation_id" = r."organisation_id", "guest_id" = r."guest_id", "stay_id" = s."id", "taxable_amount_paise" = f."subtotal_paise", "outstanding_paise" = f."total_paise" FROM "reservations" r LEFT JOIN "stays" s ON s."reservation_id" = r."id" WHERE r."id" = f."reservation_id";
ALTER TABLE "folios" ALTER COLUMN "organisation_id" SET NOT NULL;
--> statement-breakpoint
ALTER TABLE "folio_lines" ADD COLUMN "organisation_id" text;
ALTER TABLE "folio_lines" ADD COLUMN "property_id" text;
ALTER TABLE "folio_lines" ADD COLUMN "subtotal_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folio_lines" ADD COLUMN "discount_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folio_lines" ADD COLUMN "taxable_amount_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folio_lines" ADD COLUMN "tax_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folio_lines" ADD COLUMN "cgst_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folio_lines" ADD COLUMN "sgst_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folio_lines" ADD COLUMN "igst_paise" integer DEFAULT 0 NOT NULL;
ALTER TABLE "folio_lines" ADD COLUMN "source_type" text;
ALTER TABLE "folio_lines" ADD COLUMN "source_id" text;
ALTER TABLE "folio_lines" ADD COLUMN "service_date" text;
ALTER TABLE "folio_lines" ADD COLUMN "posted_by" text;
ALTER TABLE "folio_lines" ADD COLUMN "voided_at" timestamp with time zone;
ALTER TABLE "folio_lines" ADD COLUMN "voided_by" text;
ALTER TABLE "folio_lines" ADD COLUMN "void_reason" text;
UPDATE "folio_lines" l SET "organisation_id" = f."organisation_id", "property_id" = f."property_id", "subtotal_paise" = l."quantity" * l."unit_amount_paise", "taxable_amount_paise" = l."quantity" * l."unit_amount_paise", "tax_paise" = l."line_total_paise" - (l."quantity" * l."unit_amount_paise") FROM "folios" f WHERE f."id" = l."folio_id";
ALTER TABLE "folio_lines" ALTER COLUMN "organisation_id" SET NOT NULL;
ALTER TABLE "folio_lines" ALTER COLUMN "property_id" SET NOT NULL;
--> statement-breakpoint
CREATE TABLE "financial_sequences" ("property_id" text NOT NULL, "financial_year" text NOT NULL, "sequence_type" text NOT NULL, "next_value" integer DEFAULT 1 NOT NULL, CONSTRAINT "financial_sequences_property_id_financial_year_sequence_type_pk" PRIMARY KEY("property_id","financial_year","sequence_type"));
CREATE TABLE "payments" ("id" text PRIMARY KEY NOT NULL, "organisation_id" text NOT NULL, "property_id" text NOT NULL, "folio_id" text NOT NULL, "reservation_id" text NOT NULL, "payment_number" text NOT NULL, "method" text NOT NULL, "amount_paise" integer NOT NULL, "reference" text, "notes" text, "status" text DEFAULT 'RECEIVED' NOT NULL, "idempotency_key" text NOT NULL, "received_at" timestamp with time zone NOT NULL, "received_by" text NOT NULL, "reversed_at" timestamp with time zone, "reversed_by" text, "reversal_reason" text, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
CREATE TABLE "payment_refunds" ("id" text PRIMARY KEY NOT NULL, "organisation_id" text NOT NULL, "property_id" text NOT NULL, "folio_id" text NOT NULL, "payment_id" text NOT NULL, "amount_paise" integer NOT NULL, "reason" text NOT NULL, "reference" text, "status" text DEFAULT 'RECORDED' NOT NULL, "idempotency_key" text NOT NULL, "processed_at" timestamp with time zone NOT NULL, "processed_by" text NOT NULL);
CREATE TABLE "invoices" ("id" text PRIMARY KEY NOT NULL, "organisation_id" text NOT NULL, "property_id" text NOT NULL, "folio_id" text NOT NULL, "reservation_id" text NOT NULL, "guest_id" text NOT NULL, "invoice_number" text NOT NULL, "financial_year" text NOT NULL, "invoice_date" text NOT NULL, "customer_name_snapshot" text NOT NULL, "customer_company_snapshot" text, "customer_gstin_snapshot" text, "billing_address_snapshot" text, "customer_state_snapshot" text, "property_legal_name_snapshot" text NOT NULL, "property_gstin_snapshot" text, "property_address_snapshot" text, "subtotal_paise" integer NOT NULL, "discount_paise" integer NOT NULL, "taxable_amount_paise" integer NOT NULL, "cgst_paise" integer NOT NULL, "sgst_paise" integer NOT NULL, "igst_paise" integer NOT NULL, "grand_total_paise" integer NOT NULL, "status" text DEFAULT 'ISSUED' NOT NULL, "issued_at" timestamp with time zone NOT NULL, "issued_by" text NOT NULL, "cancelled_at" timestamp with time zone, "cancelled_by" text, "cancel_reason" text, "created_at" timestamp with time zone NOT NULL);
--> statement-breakpoint
ALTER TABLE "folios" ADD CONSTRAINT "folios_organisation_id_organisations_id_fk" FOREIGN KEY ("organisation_id") REFERENCES "public"."organisations"("id");
ALTER TABLE "folios" ADD CONSTRAINT "folios_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id");
ALTER TABLE "folios" ADD CONSTRAINT "folios_stay_id_stays_id_fk" FOREIGN KEY ("stay_id") REFERENCES "public"."stays"("id");
ALTER TABLE "folios" ADD CONSTRAINT "folios_closed_by_app_users_id_fk" FOREIGN KEY ("closed_by") REFERENCES "public"."app_users"("id");
ALTER TABLE "folio_lines" ADD CONSTRAINT "folio_lines_organisation_id_organisations_id_fk" FOREIGN KEY ("organisation_id") REFERENCES "public"."organisations"("id");
ALTER TABLE "folio_lines" ADD CONSTRAINT "folio_lines_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id");
ALTER TABLE "folio_lines" ADD CONSTRAINT "folio_lines_posted_by_app_users_id_fk" FOREIGN KEY ("posted_by") REFERENCES "public"."app_users"("id");
ALTER TABLE "folio_lines" ADD CONSTRAINT "folio_lines_voided_by_app_users_id_fk" FOREIGN KEY ("voided_by") REFERENCES "public"."app_users"("id");
ALTER TABLE "financial_sequences" ADD CONSTRAINT "financial_sequences_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id");
ALTER TABLE "payments" ADD CONSTRAINT "payments_folio_id_folios_id_fk" FOREIGN KEY ("folio_id") REFERENCES "public"."folios"("id");
ALTER TABLE "payments" ADD CONSTRAINT "payments_organisation_id_organisations_id_fk" FOREIGN KEY ("organisation_id") REFERENCES "public"."organisations"("id");
ALTER TABLE "payments" ADD CONSTRAINT "payments_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id");
ALTER TABLE "payments" ADD CONSTRAINT "payments_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id");
ALTER TABLE "payments" ADD CONSTRAINT "payments_received_by_app_users_id_fk" FOREIGN KEY ("received_by") REFERENCES "public"."app_users"("id");
ALTER TABLE "payments" ADD CONSTRAINT "payments_reversed_by_app_users_id_fk" FOREIGN KEY ("reversed_by") REFERENCES "public"."app_users"("id");
ALTER TABLE "payment_refunds" ADD CONSTRAINT "payment_refunds_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id");
ALTER TABLE "payment_refunds" ADD CONSTRAINT "payment_refunds_organisation_id_organisations_id_fk" FOREIGN KEY ("organisation_id") REFERENCES "public"."organisations"("id");
ALTER TABLE "payment_refunds" ADD CONSTRAINT "payment_refunds_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id");
ALTER TABLE "payment_refunds" ADD CONSTRAINT "payment_refunds_folio_id_folios_id_fk" FOREIGN KEY ("folio_id") REFERENCES "public"."folios"("id");
ALTER TABLE "payment_refunds" ADD CONSTRAINT "payment_refunds_processed_by_app_users_id_fk" FOREIGN KEY ("processed_by") REFERENCES "public"."app_users"("id");
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_folio_id_folios_id_fk" FOREIGN KEY ("folio_id") REFERENCES "public"."folios"("id");
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_organisation_id_organisations_id_fk" FOREIGN KEY ("organisation_id") REFERENCES "public"."organisations"("id");
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_property_id_properties_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."properties"("id");
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_reservation_id_reservations_id_fk" FOREIGN KEY ("reservation_id") REFERENCES "public"."reservations"("id");
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_guest_id_guests_id_fk" FOREIGN KEY ("guest_id") REFERENCES "public"."guests"("id");
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_issued_by_app_users_id_fk" FOREIGN KEY ("issued_by") REFERENCES "public"."app_users"("id");
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_cancelled_by_app_users_id_fk" FOREIGN KEY ("cancelled_by") REFERENCES "public"."app_users"("id");
CREATE UNIQUE INDEX "idx_payments_property_number" ON "payments" USING btree ("property_id","payment_number");
CREATE UNIQUE INDEX "idx_payments_folio_idempotency" ON "payments" USING btree ("folio_id","idempotency_key");
CREATE INDEX "idx_payments_folio_status" ON "payments" USING btree ("folio_id","status");
CREATE UNIQUE INDEX "idx_refunds_payment_idempotency" ON "payment_refunds" USING btree ("payment_id","idempotency_key");
CREATE INDEX "idx_refunds_folio" ON "payment_refunds" USING btree ("folio_id");
CREATE UNIQUE INDEX "idx_invoices_property_number" ON "invoices" USING btree ("property_id","invoice_number");
CREATE UNIQUE INDEX "idx_invoices_folio_issued" ON "invoices" USING btree ("folio_id") WHERE "status" = 'ISSUED';
CREATE UNIQUE INDEX "idx_room_charge_source" ON "folio_lines" USING btree ("folio_id","source_type","source_id") WHERE "voided_at" IS NULL AND "source_type" IS NOT NULL AND "source_id" IS NOT NULL;
ALTER TABLE "payments" ADD CONSTRAINT "payments_amount_positive" CHECK ("amount_paise" > 0);
ALTER TABLE "payment_refunds" ADD CONSTRAINT "refund_amount_positive" CHECK ("amount_paise" > 0);
