"use client";
import {useState} from 'react';
import {PageHeading,money,type PlatformViewProps,type Row} from '@/app/hotel-platform';
import {WorkflowForm} from '@/components/hotel/OperationalWorkspace';
export function TravelWorkspace({state,view,command,refresh,notify}:PlatformViewProps){
 const data=state.operationalData??{},rows=(key:string)=>(data[key] as Row[]|undefined)??[];
 const select=(key:string,label:string,items:Row[],display:string)=>({key,label,options:items.map(r=>({value:String(r.id),label:String(r[display])}))});
 const choice=(key:string,label:string,items:string[])=>({key,label,options:items.map(value=>({value,label:value.replaceAll('_',' ')}))});
 const inquiryFields=[{key:'customerName',label:'Customer name'},{key:'source',label:'Source'},{key:'owner',label:'Responsible person'},{key:'service',label:'Service'},{key:'estimatedValueRupees',label:'Estimated value (₹)',type:'number' as const},choice('status','Stage',['NEW','FOLLOW_UP','NEGOTIATION','CONVERTED','LOST'])];
 const configs={
  'Tours':{action:'SAVE_TOUR',rows:rows('tours'),columns:['name','departureDate','capacity','status'],fields:[select('packageId','Package',state.packages,'name'),{key:'name',label:'Tour name'},{key:'departureDate',label:'Departure date',type:'date' as const},{key:'capacity',label:'Capacity',type:'number' as const,min:1},{...select('managerId','Tour manager',rows('tourManagers'),'name'),required:false},choice('status','Status',['SELLING','CONFIRMED','COMPLETED','CANCELLED'])],editable:true},
  'Participants':{action:'ADD_PARTICIPANT',rows:rows('participants').map<Row>(r=>({...r,tour:rows('tours').find(t=>t.id===r.tourId)?.name})),columns:['name','tour','sharing','notes'],fields:[select('tourId','Tour',rows('tours').filter(r=>['SELLING','CONFIRMED'].includes(String(r.status))),'name'),{key:'name',label:'Traveller name'},choice('sharing','Sharing',['SINGLE','DOUBLE','TRIPLE']),{key:'notes',label:'Notes (no identity document numbers)',required:false}],editable:false},
  'Tour Managers':{action:'',rows:rows('tourManagers'),columns:['name','role'],fields:[],editable:false},
  'Communications':{action:'SAVE_COMMUNICATION_DRAFT',rows:rows('communicationDrafts'),columns:['channel','recipient','subject','status'],fields:[select('inquiryId','Inquiry',state.inquiries,'reference'),choice('channel','Channel',['EMAIL','WHATSAPP']),{key:'recipient',label:'Recipient'},{key:'subject',label:'Subject'},{key:'body',label:'Message'}],editable:false},
  'Inquiry CRM':{action:'CREATE_INQUIRY',rows:state.inquiries,columns:['reference','customerName','service','owner','status','estimatedValueRupees'],fields:inquiryFields,editable:true},
  'Sales Pipeline':{action:'CREATE_INQUIRY',rows:state.inquiries,columns:['reference','customerName','service','owner','status','estimatedValueRupees'],fields:inquiryFields,editable:true},
  'Follow-ups':{action:'CREATE_FOLLOW_UP',rows:state.followUps,columns:['channel','assignedToName','dueAt','status','notes'],fields:[select('inquiryId','Inquiry',state.inquiries,'reference'),choice('channel','Channel',['CALL','EMAIL','WHATSAPP','VISIT','OTHER']),{key:'dueAt',label:'Due date',type:'date' as const},{key:'assignedToName',label:'Responsible person'},{key:'notes',label:'Notes',required:false}],editable:false},
 };
 const config=configs[view as keyof typeof configs];const [editing,setEditing]=useState<Row|null>(null),[error,setError]=useState('');if(!config)return null;
 const save=async(row:Row,values:Row)=>{let action=config.action;if(row.id&&['Inquiry CRM','Sales Pipeline'].includes(view))action='UPDATE_INQUIRY';await command({...values,action,id:row.id,inquiryId:row.id??values.inquiryId,expectedVersion:row.version,expectedUpdatedAt:row.updatedAt,dueAt:values.dueAt?new Date(`${values.dueAt}T12:00:00`).toISOString():undefined});await refresh();setEditing(null);notify('Saved successfully.');};
 return <><PageHeading eyebrow="Travel & sales" title={view} description={view==='Communications'?'Saved message drafts. Delivery requires a configured email or WhatsApp provider.':view==='Tour Managers'?'Active tour managers from the staff directory. Create accounts in Hotel → Users & Permissions.':'Persisted organisation records shared across the Travel workspace.'} actions={config.action?<button className="primary-button" onClick={()=>setEditing({owner:state.actor.name,assignedToName:state.actor.name})}>Add {view==='Communications'?'draft':'record'}</button>:undefined}/>{error&&<p role="alert">{error}</p>}<div className="table-card"><table><thead><tr>{config.columns.map(c=><th key={c}>{c.replace(/Rupees$/, ' (₹)').replace(/([A-Z])/g,' $1')}</th>)}<th>Action</th></tr></thead><tbody>{config.rows.map(r=><tr key={String(r.id)}>{config.columns.map(c=><td key={c}>{c.endsWith('Rupees')?money(r[c]):String(r[c]??'—')}</td>)}<td>{config.editable&&<button className="text-button" onClick={()=>setEditing(r)}>Edit</button>}{view==='Follow-ups'&&r.status==='PENDING'&&<button className="text-button" onClick={async()=>{try{await command({action:'COMPLETE_FOLLOW_UP',followUpId:r.id,expectedVersion:r.version,status:'COMPLETED'});await refresh();}catch(e){setError(e instanceof Error?e.message:'Update failed.');}}}>Complete</button>}</td></tr>)}</tbody></table>{!config.rows.length&&<p className="empty-state">No records yet.</p>}</div>{editing&&<WorkflowForm title={`Save ${view.toLowerCase()}`} fields={config.fields} initial={editing} onClose={()=>setEditing(null)} onSave={values=>save(editing,values)}/>}</>;
}
