import {
  Armchair, ArrowLeftRight, BadgeCheck, BedDouble, BellRing, Boxes,
  CalendarCheck, CalendarDays, ChartColumn, ChartNoAxesCombined, ClipboardCheck,
  ClipboardList, Cloud, Coffee, ConciergeBell, CookingPot, CreditCard,
  FileClock, FileText, HandCoins, Hotel, KeyRound, LayoutDashboard,
  ListChecks, Mail, Map, MapPinned, MessageCircle, MessagesSquare, MonitorCheck,
  PackageSearch, Plug, Receipt, ReceiptText, RefreshCw,
  Settings, ShieldCheck, ShieldUser, Soup, Sparkles, Sun, Sunrise, Truck,
  UserRound, UsersRound, Utensils, Wallet, WifiOff, Wrench,
  type LucideIcon,
} from "lucide-react";

// Semantic keys keep icons consistent across navigation, cards and services.
export const appIcons = {
  occupancy: LayoutDashboard,
  "booking-calendar": CalendarDays,
  "front-desk": ConciergeBell,
  guest: UserRound,
  folio: ReceiptText,
  housekeeping: Sparkles,
  maintenance: Wrench,
  inventory: Boxes,
  restaurant: Utensils,
  travel: MapPinned,
  inquiry: MessagesSquare,
  offline: WifiOff,
  policy: ShieldCheck,
  payment: CreditCard,
  integrations: Plug,
  reports: ChartColumn,
  audit: FileClock,
  "cloud-network": Cloud,
  hotel: Hotel,
  breakfast: Sunrise,
  brunch: CookingPot,
  lunch: Sun,
  "high-tea": Coffee,
  dinner: Utensils,
  supper: Soup,
  "room-ready": BedDouble,
  "booking-feed": CalendarCheck,
  "arrivals-departures": ArrowLeftRight,
  staff: UsersRound,
  "wallet-alert": Wallet,
  "damage-alert": Wrench,
  "charge-receipt": Receipt,
  "waived-charge": HandCoins,
  "device-status": MonitorCheck,
  "phone-chat": MessageCircle,
  email: Mail,
  "channel-sync": RefreshCw,
  "smart-lock": KeyRound,
  "attention-queue": BellRing,
  "offline-billing": FileText,
  "receipt-verification": BadgeCheck,
  "room-types": Armchair,
  "inventory-movements": Truck,
  "lost-found": PackageSearch,
  "room-service": ConciergeBell,
  "meal-service": CookingPot,
  "menu-management": ClipboardList,
  tours: Map,
  participants: UsersRound,
  "tour-managers": ClipboardCheck,
  "sales-pipeline": ChartNoAxesCombined,
  "follow-ups": ListChecks,
  communications: MessagesSquare,
  "users-permissions": ShieldUser,
  "property-settings": Settings,
} satisfies Record<string, LucideIcon>;

export type AppGlyphName = keyof typeof appIcons;
